import { Category, Product } from "@/types/product";
import { PaymentMethod } from "@/types/payment";
import { Order } from "@/types/order";
import { UserSubscription } from "@/types/subscription";
import { SupportTicket } from "@/types/support";
import { StoreSettings, Coupon } from "@/types/settings";
import { AdminDashboardMetrics, AuditLog } from "@/types/admin";
import { User } from "@/types/auth";

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "AI & Machine Learning",
    slug: "ai-tools",
    description: "State-of-the-art AI assistants, creative models, and reasoning engines.",
    icon: "Sparkles",
    color: "from-purple-500 to-indigo-600",
    productCount: 5,
    active: true,
    sortOrder: 1,
  },
  {
    id: "cat-2",
    name: "Design & Creative",
    slug: "design-creative",
    description: "Industry-standard graphics, UI/UX, video editing, and vector suites.",
    icon: "Palette",
    color: "from-pink-500 to-rose-600",
    productCount: 5,
    active: true,
    sortOrder: 2,
  },
  {
    id: "cat-3",
    name: "Developer Tools",
    slug: "developer-tools",
    description: "IDEs, AI coding companions, CI/CD tools, and cloud environments.",
    icon: "Code2",
    color: "from-blue-500 to-cyan-600",
    productCount: 4,
    active: true,
    sortOrder: 3,
  },
  {
    id: "cat-4",
    name: "Productivity & Cloud",
    slug: "productivity-cloud",
    description: "Workspaces, cloud storage, document collaboration, and project management.",
    icon: "Briefcase",
    color: "from-emerald-500 to-teal-600",
    productCount: 3,
    active: true,
    sortOrder: 4,
  },
  {
    id: "cat-5",
    name: "Operating Systems & Office",
    slug: "os-office",
    description: "Genuine Microsoft Windows, Office 365, and utility license keys.",
    icon: "KeyRound",
    color: "from-amber-500 to-orange-600",
    productCount: 3,
    active: true,
    sortOrder: 5,
  },
  {
    id: "cat-6",
    name: "Entertainment & Streaming",
    slug: "streaming",
    description: "High-definition music, TV series, movie streaming passes.",
    icon: "Tv",
    color: "from-red-500 to-pink-600",
    productCount: 3,
    active: true,
    sortOrder: 6,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-canva-pro",
    name: "Canva Pro Subscription",
    slug: "canva-pro",
    shortDescription: "Unlimited access to premium templates, brand kit, background remover, and magic studio.",
    description: "Unlock the full creative power of Canva Pro. Access over 100+ million premium stock photos, videos, audio tracks, and graphics. Use Magic Resize, 1-click Background Remover, Brand Kits with custom fonts and palettes, and 1TB of cloud storage.",
    categoryId: "cat-2",
    category: INITIAL_CATEGORIES[1],
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    badge: "Best Seller",
    isFeatured: true,
    isPopular: true,
    isActive: true,
    deliveryType: "ACTIVATION_LINK",
    features: [
      "100M+ premium stock photos, graphics & videos",
      "Instant 1-Click Background Remover",
      "Brand Kit with custom logos, colors & fonts",
      "1TB Cloud Storage for all designs",
      "Magic Studio AI design tools",
      "Private workspace with zero sharing issues",
    ],
    deliveryInfo: "Delivered as a direct private invitation link to your own personal Canva email within 5-15 minutes.",
    importantNotes: "Works on your existing personal email or new email. 100% private workspace with no risk of design access by others.",
    faqs: [
      {
        question: "Can I use my existing Canva account?",
        answer: "Yes! You will receive an official invitation link that upgrades your existing account to Pro.",
      },
      {
        question: "Is my design data safe and private?",
        answer: "Yes, you have full private ownership of your team space and designs.",
      },
    ],
    startingPrice: 350,
    originalPrice: 750,
    discountPercentage: 53,
    rating: 4.9,
    ratingCount: 1420,
    plans: [
      {
        id: "plan-canva-1m",
        productId: "prod-canva-pro",
        name: "1 Month Pro Pass",
        durationValue: 1,
        durationUnit: "months",
        regularPrice: 450,
        salePrice: 350,
        stock: -1,
        active: true,
        sortOrder: 1,
        features: ["1 Month Validity", "Instant Invite", "Full Pro Suite", "24/7 Support"],
      },
      {
        id: "plan-canva-6m",
        productId: "prod-canva-pro",
        name: "6 Months Extended",
        durationValue: 6,
        durationUnit: "months",
        regularPrice: 1800,
        salePrice: 1150,
        stock: -1,
        active: true,
        isPopular: true,
        sortOrder: 2,
        features: ["6 Months Validity", "Save 36%", "Priority Renewal", "Replacement Warranty"],
      },
      {
        id: "plan-canva-12m",
        productId: "prod-canva-pro",
        name: "12 Months (1 Year) Pro",
        durationValue: 12,
        durationUnit: "months",
        regularPrice: 3200,
        salePrice: 1890,
        stock: -1,
        active: true,
        sortOrder: 3,
        features: ["365 Days Warranty", "Maximum Savings", "VIP Support", "Automatic Rollover"],
      },
    ],
    createdAt: "2025-01-10T10:00:00Z",
    updatedAt: "2025-02-15T10:00:00Z",
  },
  {
    id: "prod-chatgpt-plus",
    name: "ChatGPT Plus & GPT-4o Access",
    slug: "chatgpt-plus",
    shortDescription: "Official OpenAI ChatGPT Plus access with GPT-4o, DALL·E 3, Canvas, and custom GPTs.",
    description: "Supercharge your workflow with ChatGPT Plus. Get priority access during peak hours, ultra-fast response times, access to OpenAI's flagship GPT-4o model, Advanced Voice Mode, web browsing, Python code interpreter, and custom GPT builder.",
    categoryId: "cat-1",
    category: INITIAL_CATEGORIES[0],
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780efad99a?w=600&auto=format&fit=crop&q=80",
    badge: "Trending AI",
    isFeatured: true,
    isPopular: true,
    isActive: true,
    deliveryType: "ACCOUNT_CREDENTIAL",
    features: [
      "Access to GPT-4o & o1 Reasoning models",
      "DALL·E 3 Image Generation built-in",
      "Advanced Data Analysis & Python execution",
      "Custom GPTs creation and store access",
      "Zero downtime during peak hours",
      "Fast response speed with continuous updates",
    ],
    deliveryInfo: "Private dedicated credentials (Email & Password) delivered to your account dashboard with full login instructions.",
    importantNotes: "Personal dedicated account. Do not share credentials across multiple IP addresses simultaneously.",
    faqs: [
      {
        question: "Is this a shared or private account?",
        answer: "We provide dedicated private accounts with full login access and chat history preservation.",
      },
      {
        question: "Do I need a VPN to use ChatGPT in Bangladesh?",
        answer: "No VPN is required. You can log in directly on chat.openai.com.",
      },
    ],
    startingPrice: 1250,
    originalPrice: 2400,
    discountPercentage: 48,
    rating: 4.95,
    ratingCount: 890,
    plans: [
      {
        id: "plan-gpt-1m",
        productId: "prod-chatgpt-plus",
        name: "1 Month Dedicated",
        durationValue: 1,
        durationUnit: "months",
        regularPrice: 2400,
        salePrice: 1250,
        stock: 45,
        active: true,
        sortOrder: 1,
        features: ["30 Days Active", "Private Profile", "GPT-4o + o1 Access", "Replacement Warranty"],
      },
      {
        id: "plan-gpt-3m",
        productId: "prod-chatgpt-plus",
        name: "3 Months Bundle",
        durationValue: 3,
        durationUnit: "months",
        regularPrice: 7200,
        salePrice: 3450,
        stock: 20,
        active: true,
        isPopular: true,
        sortOrder: 2,
        features: ["90 Days Active", "Uninterrupted Service", "Save 52%", "VIP Priority Help"],
      },
    ],
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-02-18T10:00:00Z",
  },
  {
    id: "prod-gemini-advanced",
    name: "Google Gemini Advanced (Gemini 2.5 Pro)",
    slug: "gemini-advanced",
    shortDescription: "Google's flagship AI model with 2 Million token context, deep research, and Google Workspace integration.",
    description: "Experience the cutting edge of Google AI with Gemini Advanced. Features the groundbreaking 2M token context window capable of analyzing large codebases, books, and hour-long videos. Includes Imagen 3 image generation, deep research, 2TB Google One cloud storage, and integration inside Docs, Gmail, and Sheets.",
    categoryId: "cat-1",
    category: INITIAL_CATEGORIES[0],
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    badge: "Official Google AI",
    isFeatured: true,
    isPopular: true,
    isActive: true,
    deliveryType: "ACCOUNT_CREDENTIAL",
    features: [
      "Access to Gemini 1.5 Pro & Ultra models",
      "2 Million token context window for huge files",
      "Imagen 3 high-definition image generation",
      "Direct Google Docs, Sheets & Gmail integration",
      "2TB Google One cloud storage included",
      "Priority response speed with zero wait times",
    ],
    deliveryInfo: "Private dedicated Google credentials or family invite link dispatched directly to your order vault.",
    importantNotes: "Works worldwide with zero VPN needed. Private dedicated profile with full replacement warranty.",
    faqs: [
      {
        question: "Does this include Google One 2TB storage?",
        answer: "Yes! Gemini Advanced plans include 2TB of Google One cloud storage alongside premier AI model access.",
      },
      {
        question: "Can I use it for programming and document analysis?",
        answer: "Gemini Advanced has the largest context window (2M tokens), allowing you to upload entire codebases or 1000+ page PDFs with ease.",
      },
    ],
    startingPrice: 999,
    originalPrice: 2200,
    discountPercentage: 55,
    rating: 4.94,
    ratingCount: 540,
    plans: [
      {
        id: "plan-gemini-1m",
        productId: "prod-gemini-advanced",
        name: "1 Month Dedicated",
        durationValue: 1,
        durationUnit: "months",
        regularPrice: 2200,
        salePrice: 999,
        stock: 35,
        active: true,
        sortOrder: 1,
        features: ["1 Month Validity", "2M Context Window", "2TB Storage", "Full Warranty"],
      },
      {
        id: "plan-gemini-3m",
        productId: "prod-gemini-advanced",
        name: "3 Months Bundle",
        durationValue: 3,
        durationUnit: "months",
        regularPrice: 6600,
        salePrice: 2690,
        stock: 20,
        active: true,
        isPopular: true,
        sortOrder: 2,
        features: ["3 Months Validity", "Save 59%", "Priority Replacement", "VIP Support"],
      },
    ],
    createdAt: "2025-01-18T10:00:00Z",
    updatedAt: "2025-02-18T10:00:00Z",
  },
  {
    id: "prod-claude-pro",
    name: "Claude Pro (Anthropic Sonnet 3.5)",
    slug: "claude-pro",
    shortDescription: "5x more usage of Claude 3.5 Sonnet, Artifacts, Project Knowledge bases, and early access.",
    description: "Get the premier AI assistant for writing, coding, and complex reasoning. Claude Pro gives you 5x higher usage limits for Claude 3.5 Sonnet, ability to create custom Projects with document context, code preview Artifacts, and priority bandwidth.",
    categoryId: "cat-1",
    category: INITIAL_CATEGORIES[0],
    imageUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&auto=format&fit=crop&q=80",
    badge: "Top Coder Pick",
    isFeatured: true,
    isPopular: false,
    isActive: true,
    deliveryType: "ACCOUNT_CREDENTIAL",
    features: [
      "5x more usage for Claude 3.5 Sonnet & Opus",
      "Interactive Artifacts rendering",
      "Projects with attached docs & knowledge base",
      "200K token context window",
      "Priority bandwidth during peak hours",
    ],
    deliveryInfo: "Account credentials delivered to dashboard upon manual payment verification.",
    startingPrice: 1350,
    originalPrice: 2500,
    discountPercentage: 46,
    rating: 4.88,
    ratingCount: 420,
    plans: [
      {
        id: "plan-claude-1m",
        productId: "prod-claude-pro",
        name: "1 Month Dedicated",
        durationValue: 1,
        durationUnit: "months",
        regularPrice: 2500,
        salePrice: 1350,
        stock: 30,
        active: true,
        sortOrder: 1,
        features: ["30 Days Pro", "Clean History", "Support & Warranty"],
      },
      {
        id: "plan-claude-3m",
        productId: "prod-claude-pro",
        name: "3 Months Pro",
        durationValue: 3,
        durationUnit: "months",
        regularPrice: 7500,
        salePrice: 3800,
        stock: 15,
        active: true,
        sortOrder: 2,
        features: ["90 Days Pro", "Save 49%", "Instant Replacement Guarantee"],
      },
    ],
    createdAt: "2025-01-20T10:00:00Z",
    updatedAt: "2025-02-18T10:00:00Z",
  },
  {
    id: "prod-jetbrains-all",
    name: "JetBrains All Products Pack",
    slug: "jetbrains-all-products",
    shortDescription: "Complete suite of 16 IDEs including WebStorm, IntelliJ IDEA Ultimate, PyCharm Pro, and GoLand.",
    description: "The ultimate toolset for developers. Includes IntelliJ IDEA Ultimate, WebStorm, PhpStorm, PyCharm Professional, GoLand, Rider, CLion, DataGrip, and more. Features intelligent coding assistance, refactoring, database tools, and Git integration.",
    categoryId: "cat-3",
    category: INITIAL_CATEGORIES[2],
    imageUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80",
    badge: "Developer Must-Have",
    isFeatured: true,
    isPopular: true,
    isActive: true,
    deliveryType: "ACTIVATION_LINK",
    features: [
      "Access to all 16 JetBrains desktop IDEs",
      "IntelliJ IDEA, WebStorm, PyCharm, GoLand, Rider",
      "Official educational / professional activation",
      "Sync settings and plugins across machines",
      "Full offline license support",
    ],
    deliveryInfo: "Activation invitation sent directly to your email or direct license key assigned.",
    startingPrice: 850,
    originalPrice: 2200,
    discountPercentage: 61,
    rating: 4.96,
    ratingCount: 650,
    plans: [
      {
        id: "plan-jb-1y",
        productId: "prod-jetbrains-all",
        name: "1 Year Full Suite",
        durationValue: 12,
        durationUnit: "months",
        regularPrice: 2200,
        salePrice: 850,
        stock: -1,
        active: true,
        isPopular: true,
        sortOrder: 1,
        features: ["1 Full Year", "16 IDEs Included", "Instant Activation", "Free Updates"],
      },
      {
        id: "plan-jb-2y",
        productId: "prod-jetbrains-all",
        name: "2 Years Value Pack",
        durationValue: 24,
        durationUnit: "months",
        regularPrice: 4200,
        salePrice: 1550,
        stock: -1,
        active: true,
        sortOrder: 2,
        features: ["2 Full Years", "Zero hassle", "Priority support"],
      },
    ],
    createdAt: "2025-01-22T10:00:00Z",
    updatedAt: "2025-02-18T10:00:00Z",
  },
  {
    id: "prod-win11-pro",
    name: "Windows 11 Pro Genuine Retail Key",
    slug: "windows-11-pro-retail-key",
    shortDescription: "100% Genuine lifetime retail license key for Windows 11 Pro 32/64 bit with online activation.",
    description: "Activate your Windows 11 Pro installation permanently with an official genuine retail license key. Supports online activation directly inside Windows Settings. Unlocks BitLocker encryption, Remote Desktop, Hyper-V virtualization, Windows Sandbox, and lifetime official Microsoft updates.",
    categoryId: "cat-5",
    category: INITIAL_CATEGORIES[4],
    imageUrl: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=600&auto=format&fit=crop&q=80",
    badge: "Lifetime Key",
    isFeatured: true,
    isPopular: true,
    isActive: true,
    deliveryType: "LICENSE_KEY",
    features: [
      "100% Genuine Microsoft Retail License",
      "Lifetime activation for 1 PC",
      "Online 1-click activation in Settings",
      "BitLocker & Remote Desktop support",
      "Free lifetime Microsoft security updates",
    ],
    deliveryInfo: "Instant alphanumeric 25-character license key displayed in your customer order dashboard.",
    startingPrice: 499,
    originalPrice: 1999,
    discountPercentage: 75,
    rating: 4.98,
    ratingCount: 2310,
    plans: [
      {
        id: "plan-win-1pc",
        productId: "prod-win11-pro",
        name: "1 PC Lifetime Retail Key",
        durationValue: 1,
        durationUnit: "lifetime",
        regularPrice: 1999,
        salePrice: 499,
        stock: 120,
        active: true,
        isPopular: true,
        sortOrder: 1,
        features: ["1 PC Lifetime", "Online Activation", "Support Included"],
      },
      {
        id: "plan-win-3pc",
        productId: "prod-win11-pro",
        name: "3 PC Office Multi-Pack",
        durationValue: 1,
        durationUnit: "lifetime",
        regularPrice: 5999,
        salePrice: 1290,
        stock: 40,
        active: true,
        sortOrder: 2,
        features: ["3 Separate PC Keys", "Save extra 15%", "Lifetime Validity"],
      },
    ],
    createdAt: "2025-01-05T10:00:00Z",
    updatedAt: "2025-02-18T10:00:00Z",
  },
  {
    id: "prod-spotify-prem",
    name: "Spotify Premium Individual / Family",
    slug: "spotify-premium",
    shortDescription: "Ad-free high fidelity music listening, offline downloads, unlimited skips on your own account.",
    description: "Enjoy millions of tracks, podcasts, and audiobooks without any ad interruptions. Download your favorite music for offline playback in ultra-high 320kbps audio quality.",
    categoryId: "cat-6",
    category: INITIAL_CATEGORIES[5],
    imageUrl: "https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=600&auto=format&fit=crop&q=80",
    badge: "Music",
    isFeatured: false,
    isPopular: true,
    isActive: true,
    deliveryType: "ACTIVATION_LINK",
    features: [
      "Ad-free music listening",
      "Offline downloads on up to 5 devices",
      "Very high 320kbps audio quality",
      "Play songs in any order with unlimited skips",
      "Private upgrade on your own account",
    ],
    deliveryInfo: "Invite link sent to join our official family plan or direct individual subscription upgrade.",
    startingPrice: 199,
    originalPrice: 450,
    discountPercentage: 56,
    rating: 4.85,
    ratingCount: 780,
    plans: [
      {
        id: "plan-spot-1m",
        productId: "prod-spotify-prem",
        name: "1 Month Pass",
        durationValue: 1,
        durationUnit: "months",
        regularPrice: 450,
        salePrice: 199,
        stock: -1,
        active: true,
        sortOrder: 1,
      },
      {
        id: "plan-spot-3m",
        productId: "prod-spotify-prem",
        name: "3 Months Family Slot",
        durationValue: 3,
        durationUnit: "months",
        regularPrice: 1200,
        salePrice: 499,
        stock: -1,
        active: true,
        isPopular: true,
        sortOrder: 2,
      },
      {
        id: "plan-spot-6m",
        productId: "prod-spotify-prem",
        name: "6 Months Plan",
        durationValue: 6,
        durationUnit: "months",
        regularPrice: 2400,
        salePrice: 890,
        stock: -1,
        active: true,
        sortOrder: 3,
      },
    ],
    createdAt: "2025-01-25T10:00:00Z",
    updatedAt: "2025-02-18T10:00:00Z",
  },
  {
    id: "prod-midjourney",
    name: "Midjourney Pro Tier Access",
    slug: "midjourney-pro",
    shortDescription: "Ultra-photorealistic AI image generation with Fast GPU hours, stealth mode, and web gallery.",
    description: "Create breathtaking, cinematic artwork and commercial product designs with Midjourney. Includes 30 hours of fast GPU time, unlimited Relax mode generations, Stealth mode to keep images private, and concurrent job processing.",
    categoryId: "cat-1",
    category: INITIAL_CATEGORIES[0],
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    badge: "AI Art",
    isFeatured: true,
    isPopular: false,
    isActive: true,
    deliveryType: "ACCOUNT_CREDENTIAL",
    features: [
      "30 Fast GPU hours per month",
      "Unlimited Relaxed generations",
      "Stealth mode (keep designs private)",
      "Maximum upscale resolution & inpainting",
      "Commercial usage license included",
    ],
    deliveryInfo: "Discord account access credentials or dedicated server invite credentials provided.",
    startingPrice: 1850,
    originalPrice: 3500,
    discountPercentage: 47,
    rating: 4.92,
    ratingCount: 310,
    plans: [
      {
        id: "plan-mj-1m",
        productId: "prod-midjourney",
        name: "1 Month Standard",
        durationValue: 1,
        durationUnit: "months",
        regularPrice: 3500,
        salePrice: 1850,
        stock: 12,
        active: true,
        isPopular: true,
        sortOrder: 1,
      },
    ],
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-02-18T10:00:00Z",
  },
  {
    id: "prod-ms365",
    name: "Microsoft 365 Family (1TB Cloud)",
    slug: "microsoft-365-family",
    shortDescription: "Word, Excel, PowerPoint, Outlook + 1TB OneDrive cloud storage for your own Microsoft account.",
    description: "Get the complete productivity package on up to 5 devices simultaneously. Word, Excel, PowerPoint, Outlook, OneNote, and 1TB secure OneDrive cloud storage with ransomware detection.",
    categoryId: "cat-5",
    category: INITIAL_CATEGORIES[4],
    imageUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80",
    badge: "Official",
    isFeatured: false,
    isPopular: true,
    isActive: true,
    deliveryType: "ACTIVATION_LINK",
    features: [
      "1TB Private OneDrive Cloud Storage",
      "Word, Excel, PowerPoint, Outlook desktop apps",
      "Install on up to 5 PCs / Macs / Phones",
      "Official upgrade to your existing Microsoft ID",
      "Automatic synchronization & autosave",
    ],
    deliveryInfo: "Official Microsoft family invite link sent to your email.",
    startingPrice: 450,
    originalPrice: 1200,
    discountPercentage: 62,
    rating: 4.91,
    ratingCount: 940,
    plans: [
      {
        id: "plan-ms-6m",
        productId: "prod-ms365",
        name: "6 Months Pass",
        durationValue: 6,
        durationUnit: "months",
        regularPrice: 1200,
        salePrice: 450,
        stock: -1,
        active: true,
        sortOrder: 1,
      },
      {
        id: "plan-ms-12m",
        productId: "prod-ms365",
        name: "12 Months (1 Year)",
        durationValue: 12,
        durationUnit: "months",
        regularPrice: 2200,
        salePrice: 790,
        stock: -1,
        active: true,
        isPopular: true,
        sortOrder: 2,
      },
    ],
    createdAt: "2025-02-05T10:00:00Z",
    updatedAt: "2025-02-18T10:00:00Z",
  },
];

export const INITIAL_PAYMENT_METHODS: PaymentMethod[] = [
  {
    id: "pm-bkash",
    provider: "bkash",
    displayName: "bKash (Send Money / Merchant)",
    paymentNumber: "01789123456",
    accountType: "Personal",
    instructions:
      "1. Go to your bKash app or dial *247#\n2. Select 'Send Money' option\n3. Enter our Personal Number: 01789123456\n4. Enter the exact total amount\n5. Enter reference: (Your Name)\n6. Enter your PIN and complete transfer\n7. Copy the 10-digit Transaction ID (TrxID) and paste it below.",
    active: true,
    sortOrder: 1,
  },
  {
    id: "pm-nagad",
    provider: "nagad",
    displayName: "Nagad (Send Money / Merchant)",
    paymentNumber: "01876543210",
    accountType: "Personal",
    instructions:
      "1. Open your Nagad app or dial *167#\n2. Select 'Send Money'\n3. Enter our Nagad Number: 01876543210\n4. Enter the total amount\n5. Complete payment and copy the 8-character Transaction ID\n6. Enter the Sender number and TrxID in the form below.",
    active: true,
    sortOrder: 2,
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: "cp-welcome",
    code: "WELCOME10",
    description: "10% off for new customers",
    discountType: "percentage",
    discountValue: 10,
    minOrderAmount: 300,
    maxDiscount: 200,
    usedCount: 48,
    active: true,
  },
  {
    id: "cp-save50",
    code: "SAVE50",
    description: "৳50 Flat discount on orders over ৳500",
    discountType: "fixed",
    discountValue: 50,
    minOrderAmount: 500,
    usedCount: 112,
    active: true,
  },
];

export const INITIAL_SETTINGS: StoreSettings = {
  storeName: "DigiVault Marketplace",
  tagline: "Premium Digital Tools & Subscriptions at Unbeatable Prices",
  logoUrl: "/images/logo.png",
  supportEmail: "support@digivault.shop",
  supportPhone: "+880 1789 123456",
  whatsappNumber: "+8801789123456",
  currency: "BDT",
  currencySymbol: "৳",
  orderPrefix: "DV-",
  paymentInstructions: "Please make manual payment using bKash or Nagad. Orders are verified and fulfilled within 10-30 minutes.",
  facebookUrl: "https://facebook.com/digivault",
  telegramUrl: "https://t.me/digivault_bd",
  discordUrl: "https://discord.gg/digivault",
  seoTitle: "DigiVault — Premium Digital Tools, Subscriptions & License Keys",
  seoDescription: "Buy Canva Pro, ChatGPT Plus, JetBrains, Windows 11 keys and subscriptions with instant bKash & Nagad payments.",
  termsUrl: "/terms",
  privacyUrl: "/privacy",
};

export const INITIAL_ORDERS: Order[] = [
  {
    id: "ord-1001",
    orderNumber: "DV-84920",
    customerId: "usr-demo-1",
    customerName: "Nafij Islam",
    customerEmail: "nafij@example.com",
    customerPhone: "01712345678",
    items: [
      {
        id: "item-1",
        productId: "prod-canva-pro",
        productName: "Canva Pro Subscription",
        productSlug: "canva-pro",
        productImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
        planId: "plan-canva-12m",
        planName: "12 Months (1 Year) Pro",
        durationValue: 12,
        durationUnit: "months",
        price: 1890,
        quantity: 1,
      },
    ],
    subtotal: 1890,
    discountAmount: 0,
    totalAmount: 1890,
    currency: "৳",
    paymentMethodId: "pm-bkash",
    paymentMethod: INITIAL_PAYMENT_METHODS[0],
    senderNumber: "01712345678",
    transactionId: "BL79XQ8210",
    paymentNote: "Paid via bKash App",
    paymentSubmittedAt: "2025-02-25T14:30:00Z",
    paymentVerifiedAt: "2025-02-25T14:35:00Z",
    status: "FULFILLED",
    deliveryType: "ACTIVATION_LINK",
    deliveryData: {
      activationLink: "https://www.canva.com/brand/join?token=dv_pro_84920x9182",
      instructions: "Click the link to accept your Canva Pro team invite. All your designs remain 100% private.",
      fulfilledAt: "2025-02-25T14:38:00Z",
    },
    timeline: [
      {
        id: "tl-1",
        status: "PENDING_PAYMENT",
        title: "Order Placed",
        description: "Order received by system.",
        timestamp: "2025-02-25T14:28:00Z",
        completed: true,
      },
      {
        id: "tl-2",
        status: "PENDING_PAYMENT_VERIFICATION",
        title: "Payment Submitted",
        description: "bKash TrxID BL79XQ8210 submitted for verification.",
        timestamp: "2025-02-25T14:30:00Z",
        completed: true,
      },
      {
        id: "tl-3",
        status: "PAYMENT_APPROVED",
        title: "Payment Approved",
        description: "Payment verified by administrator.",
        timestamp: "2025-02-25T14:35:00Z",
        completed: true,
      },
      {
        id: "tl-4",
        status: "PROCESSING",
        title: "Order Processing",
        description: "Generating secure invitation access token.",
        timestamp: "2025-02-25T14:36:00Z",
        completed: true,
      },
      {
        id: "tl-5",
        status: "FULFILLED",
        title: "Delivered",
        description: "Product delivery info ready in customer dashboard.",
        timestamp: "2025-02-25T14:38:00Z",
        completed: true,
      },
    ],
    createdAt: "2025-02-25T14:28:00Z",
    updatedAt: "2025-02-25T14:38:00Z",
  },
  {
    id: "ord-1002",
    orderNumber: "DV-84921",
    customerId: "usr-demo-1",
    customerName: "Nafij Islam",
    customerEmail: "nafij@example.com",
    customerPhone: "01712345678",
    items: [
      {
        id: "item-2",
        productId: "prod-chatgpt-plus",
        productName: "ChatGPT Plus & GPT-4o Access",
        productSlug: "chatgpt-plus",
        productImage: "https://images.unsplash.com/photo-1677442136019-21780efad99a?w=600&auto=format&fit=crop&q=80",
        planId: "plan-gpt-1m",
        planName: "1 Month Dedicated",
        durationValue: 1,
        durationUnit: "months",
        price: 1250,
        quantity: 1,
      },
    ],
    subtotal: 1250,
    discountAmount: 100,
    couponCode: "WELCOME10",
    totalAmount: 1150,
    currency: "৳",
    paymentMethodId: "pm-nagad",
    paymentMethod: INITIAL_PAYMENT_METHODS[1],
    senderNumber: "01898765432",
    transactionId: "NG8824AA19",
    paymentNote: "Nagad send money done",
    paymentSubmittedAt: "2025-02-28T09:15:00Z",
    status: "PENDING_PAYMENT_VERIFICATION",
    deliveryType: "ACCOUNT_CREDENTIAL",
    timeline: [
      {
        id: "tl-10",
        status: "PENDING_PAYMENT",
        title: "Order Placed",
        description: "Order created for ChatGPT Plus.",
        timestamp: "2025-02-28T09:12:00Z",
        completed: true,
      },
      {
        id: "tl-11",
        status: "PENDING_PAYMENT_VERIFICATION",
        title: "Payment Submitted",
        description: "Nagad TrxID NG8824AA19 submitted. Awaiting admin review.",
        timestamp: "2025-02-28T09:15:00Z",
        completed: true,
      },
      {
        id: "tl-12",
        status: "PAYMENT_APPROVED",
        title: "Payment Approved",
        description: "Admin verification pending.",
        timestamp: "",
        completed: false,
      },
      {
        id: "tl-13",
        status: "PROCESSING",
        title: "Processing",
        description: "Account provisioning.",
        timestamp: "",
        completed: false,
      },
      {
        id: "tl-14",
        status: "FULFILLED",
        title: "Delivered",
        description: "Credentials will be visible here once verified.",
        timestamp: "",
        completed: false,
      },
    ],
    createdAt: "2025-02-28T09:12:00Z",
    updatedAt: "2025-02-28T09:15:00Z",
  },
  {
    id: "ord-1003",
    orderNumber: "DV-84922",
    customerId: "usr-demo-2",
    customerName: "Tariqul Hasan",
    customerEmail: "tariq@gmail.com",
    customerPhone: "01911223344",
    items: [
      {
        id: "item-3",
        productId: "prod-win11-pro",
        productName: "Windows 11 Pro Genuine Retail Key",
        productSlug: "windows-11-pro-retail-key",
        productImage: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=600&auto=format&fit=crop&q=80",
        planId: "plan-win-1pc",
        planName: "1 PC Lifetime Retail Key",
        durationValue: 1,
        durationUnit: "lifetime",
        price: 499,
        quantity: 1,
      },
    ],
    subtotal: 499,
    discountAmount: 0,
    totalAmount: 499,
    currency: "৳",
    paymentMethodId: "pm-bkash",
    paymentMethod: INITIAL_PAYMENT_METHODS[0],
    senderNumber: "01911223344",
    transactionId: "BKV819934K",
    status: "FULFILLED",
    deliveryType: "LICENSE_KEY",
    deliveryData: {
      licenseKey: "W269N-WFGWX-YVC9B-4J6C9-T83GX",
      instructions: "Go to Windows Settings -> System -> Activation -> Change product key and enter this license key. Then click Activate.",
      fulfilledAt: "2025-02-20T11:00:00Z",
    },
    timeline: [
      {
        id: "tl-20",
        status: "PENDING_PAYMENT",
        title: "Order Placed",
        description: "Order created.",
        timestamp: "2025-02-20T10:50:00Z",
        completed: true,
      },
      {
        id: "tl-21",
        status: "PENDING_PAYMENT_VERIFICATION",
        title: "Payment Submitted",
        description: "bKash TrxID submitted.",
        timestamp: "2025-02-20T10:52:00Z",
        completed: true,
      },
      {
        id: "tl-22",
        status: "PAYMENT_APPROVED",
        title: "Payment Approved",
        description: "Payment verified.",
        timestamp: "2025-02-20T10:55:00Z",
        completed: true,
      },
      {
        id: "tl-23",
        status: "PROCESSING",
        title: "Processing",
        description: "Key allocation.",
        timestamp: "2025-02-20T10:58:00Z",
        completed: true,
      },
      {
        id: "tl-24",
        status: "FULFILLED",
        title: "Delivered",
        description: "License key generated.",
        timestamp: "2025-02-20T11:00:00Z",
        completed: true,
      },
    ],
    createdAt: "2025-02-20T10:50:00Z",
    updatedAt: "2025-02-20T11:00:00Z",
  },
];

export const INITIAL_SUBSCRIPTIONS: UserSubscription[] = [
  {
    id: "sub-1",
    orderId: "ord-1001",
    productId: "prod-canva-pro",
    productName: "Canva Pro Subscription",
    productSlug: "canva-pro",
    productImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    planName: "12 Months (1 Year) Pro",
    startDate: "2025-02-25T14:38:00Z",
    expiryDate: "2026-02-25T14:38:00Z",
    status: "ACTIVE",
    autoRenewAvailable: true,
    deliveryData: {
      activationLink: "https://www.canva.com/brand/join?token=dv_pro_84920x9182",
      instructions: "Direct team invitation link. Your designs are private.",
    },
  },
  {
    id: "sub-2",
    orderId: "ord-1002",
    productId: "prod-chatgpt-plus",
    productName: "ChatGPT Plus (GPT-4o)",
    productSlug: "chatgpt-plus",
    productImage: "https://images.unsplash.com/photo-1677442136019-21780efad99a?w=600&auto=format&fit=crop&q=80",
    planName: "1 Month Dedicated",
    startDate: "2025-02-01T10:00:00Z",
    expiryDate: "2025-03-03T10:00:00Z",
    status: "EXPIRING_SOON",
    autoRenewAvailable: true,
    deliveryData: {
      emailOrUsername: "pro.member88@digivault.access",
      password: "VaultSecuredPass992!",
      loginUrl: "https://chatgpt.com/auth/login",
      instructions: "Do not change password or share access across multiple devices simultaneously.",
    },
  },
];

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: "tkt-101",
    ticketNumber: "TCK-4091",
    customerId: "usr-demo-1",
    customerName: "Nafij Islam",
    customerEmail: "nafij@example.com",
    subject: "Question about Canva Pro team invite renewal",
    category: "Product Issue",
    priority: "MEDIUM",
    status: "RESOLVED",
    orderId: "ord-1001",
    messages: [
      {
        id: "msg-1",
        ticketId: "tkt-101",
        senderId: "usr-demo-1",
        senderName: "Nafij Islam",
        senderRole: "customer",
        message: "Hi, will I lose any created designs when renewing after 12 months?",
        createdAt: "2025-02-26T10:00:00Z",
      },
      {
        id: "msg-2",
        ticketId: "tkt-101",
        senderId: "admin-1",
        senderName: "Support Team (Alex)",
        senderRole: "support",
        message: "Hello Nafij! No, your designs and templates are permanently preserved in your personal workspace. You can seamlessly renew at any time.",
        createdAt: "2025-02-26T10:15:00Z",
      },
    ],
    createdAt: "2025-02-26T10:00:00Z",
    updatedAt: "2025-02-26T10:15:00Z",
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: "usr-demo-1",
    name: "Nafij Islam",
    email: "nafij@example.com",
    phone: "01712345678",
    role: "customer",
    createdAt: "2025-01-01T00:00:00Z",
    isEmailVerified: true,
  },
  {
    id: "usr-admin-1",
    name: "Admin Superuser",
    email: "admin@digivault.shop",
    phone: "01789123456",
    role: "superadmin",
    createdAt: "2025-01-01T00:00:00Z",
    isEmailVerified: true,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "log-1",
    adminId: "usr-admin-1",
    adminName: "Admin Superuser",
    action: "ORDER_FULFILLED",
    targetType: "ORDER",
    targetId: "ord-1001",
    details: "Delivered Canva Pro activation link to nafij@example.com",
    createdAt: "2025-02-25T14:38:00Z",
  },
  {
    id: "log-2",
    adminId: "usr-admin-1",
    adminName: "Admin Superuser",
    action: "PAYMENT_APPROVED",
    targetType: "PAYMENT",
    targetId: "ord-1001",
    details: "Approved bKash TrxID BL79XQ8210 (Amount: ৳1,890)",
    createdAt: "2025-02-25T14:35:00Z",
  },
  {
    id: "log-3",
    adminId: "usr-admin-1",
    adminName: "Admin Superuser",
    action: "PRODUCT_CREATED",
    targetType: "PRODUCT",
    targetId: "prod-midjourney",
    details: "Added new product 'Midjourney Pro Tier Access' with 1 plan",
    createdAt: "2025-02-01T10:00:00Z",
  },
];
